from .futurasciences_crawling_job import FuturaSciencesCrawlingJob
from .liberation_crawling_job import LiberationCrawlingJob
from .nouvelobs_crawling_job import NouvelObsCrawlingJob
from .telerama_crawling_job import TeleramaCrawlingJob
from .lefigaro_crawling_job import LeFigaroCrawlingJob
from .lemonde_crawling_job import LeMondeCrawlingJob